# The Windows launcher. Two jobs, the same two as bootstrap.sh: hand over to Node when it is here,
# and finish design-only when it is not.
#
# Windows PowerShell 5.1 — what every Windows 10/11 has, and therefore what this targets. No `??`,
# no ternary, no `-AsHashtable`: all three are PowerShell 7 and would fail on the exact machine this
# file exists for. `powershell.exe`, never `pwsh`.
Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

$Root = Split-Path -Parent $MyInvocation.MyCommand.Path

# text-begin (generated by scripts/gen-launcher-text.mjs — do not edit)
$SERVER_KEY = 'servicenow'
$MSG_NODE_WIN = 'winget install OpenJS.NodeJS.LTS'
$MSG_GIT_WIN = 'winget install Git.Git'
$MSG_CLAUDE = 'install Claude Code from https://code.claude.com/docs/en/setup, then re-run'
$MSG_NET = 'check your network, or set HTTPS_PROXY / NO_PROXY for your environment, and re-run'
$MSG_DNS_FMT = 'cannot reach {0} (DNS) — check your network and re-run'
$MSG_UPSTREAM_LOCAL = 'corpus upstream is local — no probe'
$MSG_UPSTREAM_SCHEME_FMT = 'corpus upstream is {0} — not probed (this check speaks HTTPS)'
$MSG_TLS = 'TLS interception detected — set GIT_SSL_CAINFO (or git config http.sslCAInfo) to your corporate CA bundle and re-run; the MCP server needs the same bundle via NODE_EXTRA_CA_CERTS (docs/TROUBLESHOOTING.md)'
$MSG_DOCTOR = 'DOCTOR: unavailable until Node 20+ is installed (design-only is complete)'
$MSG_MODE = 'Mode: design-only'
$MSG_NEXT = 'Next: run `claude` here. You will see one workspace-trust dialog — answer Yes.
      (If you are already inside Claude Code in this folder: exit it and start `claude` again.)
      Add a live instance later with snowarch.cmd mode live, or /snowarch setup-instance inside Claude.'
$MSG_CITATIONS = 'citations: not verified until Node 20+ is installed'
# text-end

. "$Root\tools\snowarch\launcher\docs-recipe.ps1"

$Mode = 'design'; $Docs = 'sparse'; $Yes = $false; $Reset = $false; $SkipClaude = $false
$NodeOnly = $false; $Orig = @()

# `Set-Content -Encoding UTF8` on 5.1 means UTF-8 WITH a BOM, and every file written below is
# read back by something that calls JSON.parse — where a leading BOM is a syntax error, not a
# hint. .NET writes it without one. (Found by CI: Node refused the state this file had just
# written, on the only platform that could have shown it.)
function Write-Json([string]$Path, $Value, [int]$Depth) {
  $json = $Value | ConvertTo-Json -Depth $Depth
  [System.IO.File]::WriteAllText($Path, $json, (New-Object System.Text.UTF8Encoding($false)))
}
function Say([string]$Text) { Write-Host $Text }
function Step([string]$Id, [string]$Title, [string]$Status) { Write-Host ("[{0}/09] {1} … {2}" -f $Id, $Title, $Status) }
function Die([string]$Id, [string]$Cause, [string]$Remedy, [int]$Code) {
  Write-Host ("FAIL {0}: {1}" -f $Id, $Cause)
  if ($Remedy) { Write-Host ("Remedy: {0}" -f $Remedy) }
  exit $Code
}
# The floors, from the generated config: one key per line, which ARC-06-S14 asserts. Read with a
# regex rather than ConvertFrom-Json so the launcher needs nothing of the JSON it cannot parse.
function Floor([string]$Name) {
  $line = Select-String -Path "$Root\engine.config.json" -Pattern ('"' + $Name + '": *"([0-9][0-9.]*)"') | Select-Object -First 1
  if (-not $line) { return '' }
  return $line.Matches[0].Groups[1].Value
}
function VersionGe([string]$Have, [string]$Want) {
  $a = ($Have -split '\.'); $b = ($Want -split '\.')
  for ($i = 0; $i -lt 3; $i++) {
    $x = 0; $y = 0
    if ($i -lt $a.Length) { $x = [int]($a[$i] -replace '[^0-9]', '0') }
    if ($i -lt $b.Length) { $y = [int]($b[$i] -replace '[^0-9]', '0') }
    if ($x -gt $y) { return $true }
    if ($x -lt $y) { return $false }
  }
  return $true
}

# One pass. `--mode live` arrives as two arguments and `--mode=live` as one; a second scanning loop
# for the pair form would be a second place for the two to disagree.
for ($i = 0; $i -lt $args.Length; $i++) {
  $a = [string]$args[$i]
  $Orig += $a
  switch -Regex ($a) {
    '^--mode$'          { if ($i + 1 -lt $args.Length) { $i++; $Mode = [string]$args[$i]; $Orig += $Mode } ; break }
    '^--mode=(.+)$'     { $Mode = $Matches[1]; break }
    '^--docs$'          { if ($i + 1 -lt $args.Length) { $i++; $Docs = [string]$args[$i]; $Orig += $Docs } ; break }
    '^--docs=(.+)$'     { $Docs = $Matches[1]; break }
    '^--yes$'           { $Yes = $true; break }
    '^--reset$'         { $Reset = $true; break }
    '^--skip-claude-check$' { $SkipClaude = $true; break }
    '^--(from|instance-file)(=.*)?$' { $NodeOnly = $true; break }
    '^--json$'          { $NodeOnly = $true; break }
    '^(--help|-h)$'     { Say 'usage: .\bootstrap.cmd [--mode design|live] [--docs sparse|full|skip] [--yes] [--reset]'; exit 0 }
  }
}

# The `✔` and `—` in the shared sentences are UTF-8, and TWO things have to be right for them to
# arrive intact. This file carries a UTF-8 BOM, because 5.1 reads a BOM-less file as the ANSI code
# page and would mangle them before a single line runs; and the console needs telling too, since
# conhost defaults to a code page that prints them as mojibake. A host with no console (a service,
# a redirected pipe) throws on the second one, which is not a reason to stop bootstrapping.
try { [Console]::OutputEncoding = [Text.Encoding]::UTF8 }
catch { Write-Verbose ('console encoding left as-is: ' + $_.Exception.Message) }

if ((Get-Location).Path -ne $Root) {
  Die 'B00' 'not at the repository root' ('cd /d "' + $Root + '" && .\bootstrap.cmd') 3
}

if ($Reset) {
  Remove-Item -Force -ErrorAction SilentlyContinue "$Root\.local\bootstrap-state.json", "$Root\.local\doctor-last.json"
  Say 'reset: bootstrap state cleared (.local/instances.json and .local/config.json untouched)'
  exit 0
}

# The hand-over. Everything below runs only when Node cannot.
$NodeMajor = ''
if (Get-Command node -ErrorAction SilentlyContinue) {
  # No embedded double quotes in the argument: PowerShell hands native commands their arguments
  # through a cmd-style rewrite that eats them, so `split(".")` reached node as `split(.)` and it
  # answered with a syntax error. Ask for the whole version and split it here, where the rules are
  # PowerShell's own. (CI, again — with Node present this time.)
  $NodeVersion = (& node -p 'process.versions.node' 2>$null)
  if ($NodeVersion) { $NodeMajor = ($NodeVersion -split '\.')[0] }
}
if ($NodeMajor -and (VersionGe ("$NodeMajor.0.0") (Floor 'node'))) {
  # Our spawn, so the session variable is SET rather than inherited (ARC-06-S08). PowerShell has no
  # `exec`: the parent waits and forwards the child's code, which is what `$LASTEXITCODE` carries.
  $env:CLAUDE_PROJECT_DIR = $Root
  & node "$Root\tools\snowarch\bin\snowarch.mjs" bootstrap @args
  exit $LASTEXITCODE
}

if ($NodeOnly) { Die 'B00' 'that flag needs Node.js 20+' $MSG_NODE_WIN 3 }
if ($Mode -eq 'live') { Die 'B00' 'live mode needs Node.js 20+' $MSG_NODE_WIN 3 }

# B00 preflight
$GitRaw = ''
if (Get-Command git -ErrorAction SilentlyContinue) { $GitRaw = (& git --version) }
$GitV = ''
if ($GitRaw -match 'git version ([0-9][0-9.]*)') { $GitV = $Matches[1] }
if (-not $GitV) { Die 'B00' 'git not found' $MSG_GIT_WIN 3 }
if (-not (VersionGe $GitV (Floor 'git'))) { Die 'B00' ("git $GitV found, >= " + (Floor 'git') + ' required') $MSG_GIT_WIN 3 }
Say "ok B00 git: $GitV"

if ($SkipClaude) {
  Say 'WARN B00: Claude Code check skipped (--skip-claude-check)'
} else {
  $ClaudeV = ''
  if (Get-Command claude -ErrorAction SilentlyContinue) {
    $raw = (& claude --version 2>$null)
    if ($raw -match '([0-9]+\.[0-9]+\.[0-9]+)') { $ClaudeV = $Matches[1] }
  }
  if (-not $ClaudeV) { Die 'B00' 'Claude Code not found on PATH' $MSG_CLAUDE 3 }
  if (-not (VersionGe $ClaudeV (Floor 'claudeCode'))) {
    Die 'B00' ("Claude Code $ClaudeV found, >= " + (Floor 'claudeCode') + ' required') $MSG_CLAUDE 3
  }
  Say "ok B00 claudeCode: $ClaudeV"
}

$FreeBytes = (Get-PSDrive -Name ($Root.Substring(0, 1)) -ErrorAction SilentlyContinue).Free
if (-not $FreeBytes) { $FreeBytes = 0 }
if ($FreeBytes -lt 1073741824) { Die 'B00' 'less than 1 GiB free' ("free up space on $Root") 3 }
Say ("ok B00 disk: {0} GB free" -f [int]($FreeBytes / 1073741824))

# ARC-09-C29: the host THIS RUN will contact, which is the corpus remote (B02 fetches it). The
# product repository is never contacted by a bootstrap — `upgrade` uses the checkout's own
# `origin` — so probing it was asking about one host and staying silent about another.
$UpLine = Select-String -Path "$Root\engine.config.json" -Pattern '"upstream": *"([^"]*)"' | Select-Object -First 1
$Upstream = if ($UpLine) { $UpLine.Matches[0].Groups[1].Value } else { '' }
if ($Upstream -match '^https?://') {
  $UpHost = ([uri]$Upstream).Host
  $env:GIT_TERMINAL_PROMPT = '0'
  # `-h` is deliberately absent — see the note in bootstrap.sh: with it the pattern matches no head
  # ref and git exits 2 in silence, which each launcher read differently. Same command both sides.
  $NetErr = (& git -c http.lowSpeedLimit=1000 -c http.lowSpeedTime=20 ls-remote --exit-code $Upstream HEAD 2>&1 | Out-String)
  if ($LASTEXITCODE -ne 0) {
    if ($NetErr -match 'ould not resolve host') { Die 'B00' ($MSG_DNS_FMT -f $UpHost) $MSG_NET 3 }
    if ($NetErr -match 'SSL certificate problem') { Die 'B00' $MSG_TLS $MSG_NET 3 }
    Die 'B00' ("cannot reach {0}" -f $UpHost) $MSG_NET 3
  }
  Say ("ok B00 network: {0} reachable" -f $UpHost)
} elseif ($Upstream -match '^file://') {
  # `file://` BEFORE the scheme arm, or a local upstream is reported as an unspeakable remote.
  Say ("ok B00 network: {0}" -f $MSG_UPSTREAM_LOCAL)
} elseif ($Upstream -match '^([a-z][a-z0-9+.-]*)://') {
  # A remote this probe cannot speak to is NOT reported as local: same outcome, different claim.
  Say ("ok B00 network: {0}" -f ($MSG_UPSTREAM_SCHEME_FMT -f $Matches[1]))
} else {
  # `file://` or a bare path: nothing leaves the machine, and the line says so rather than the
  # check quietly not happening.
  Say ("ok B00 network: {0}" -f $MSG_UPSTREAM_LOCAL)
}
Say ("ok B00 node: note: Node.js not found — design-only only; live mode needs Node 20+ ({0})" -f $MSG_NODE_WIN)
Step 'B00' 'preflight' 'ok'

if (-not $Yes) {
  $DocsNote = ''
  if ($Docs -ne 'skip') {
    $areas = @(Get-Content "$Root\vendor\docs-areas.txt" | Where-Object { $_.Trim() -ne '' })
    $DocsNote = " ($($areas.Length) areas)"
  }
  Say ("Plan: Mode design-only (fixed — Node.js 20+ not found) · Docs {0}{1}" -f $Docs, $DocsNote)
  Say 'Enter = run · d = docs full · s = docs skip · q = quit'
  $answer = Read-Host
  if ($answer -eq 'd') { $Docs = 'full' }
  if ($answer -eq 's') { $Docs = 'skip' }
  if ($answer -eq 'q') { exit 0 }
}

$Started = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
$StepStates = New-Object System.Collections.Specialized.OrderedDictionary
function Save-State {
  if (-not (Test-Path "$Root\.local")) { New-Item -ItemType Directory -Path "$Root\.local" | Out-Null }
  $pinLine = Select-String -Path "$Root\engine.config.json" -Pattern '"pin": *"([0-9a-f]*)"' | Select-Object -First 1
  $state = [ordered]@{
    version = 1; product = 'snowarch'; mode = 'design-only'
    docs = [ordered]@{ mode = $Docs; pin = $pinLine.Matches[0].Groups[1].Value }
    node = [ordered]@{ present = $false; version = $null }
    writer = 'powershell'; platform = 'win32'
    registration = 'project'; registrationReason = 'default'; hooksDisabledByBootstrap = $false
    # No chmod on Windows: the directory inherits the user profile's ACL, and the state says so
    # rather than implying a mode nobody applied.
    fileModes = 'acl-inherited'
    startedAt = $Started; updatedAt = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
    steps = $StepStates
  }
  Write-Json "$Root\.local\bootstrap-state.json" $state 5
}
# `$Ms` is the measured duration, when the step measured itself. `inputsHash` stays null on
# purpose: this launcher TIMES a step, it never caches one.
function Record([string]$Id, [string]$Status, [int]$Ms = 0) {
  $StepStates[$Id] = [ordered]@{
    status = $Status; inputsHash = $null
    finishedAt = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ'); durationMs = $Ms
  }
  Save-State
}

Record 'B00' 'ok'

& git diff --quiet HEAD -- .mcp.json .claude/settings.json
if ($LASTEXITCODE -ne 0) {
  Die 'B01' '.mcp.json or .claude/settings.json differs from the committed version' 'run: git checkout -- .mcp.json   (never edit this file; per-machine values belong in .claude/settings.local.json)' 1
}
Step 'B01' 'workspace' 'ok'; Record 'B01' 'ok'

if ($Docs -eq 'skip') {
  Step 'B02' 'docs' 'skipped (--docs skip) — the doctor will report the corpus as FAIL until you run ./snowarch docs sync'
  Record 'B02' 'skipped'
} else {
  $watch = [System.Diagnostics.Stopwatch]::StartNew()
  # $LASTEXITCODE is NOT the check here and never was a sound one: the recipe's two `submodule`
  # steps are allowed to fail (the Node path swallows them too), so their exit code would condemn a
  # good install — and a fatal step now THROWS, which no exit-code check ever sees. The throw is
  # what is caught.
  #
  # $corpusPre decides what the failure may delete: the recipe's first step is a clone, and a clone
  # refuses a non-empty directory, so a half-finished run left behind makes MSG_NET's "re-run"
  # false. Remove only a directory THIS run created; never one that was already there.
  $corpusPre = Test-Path "$Root\vendor\ServiceNowDocs"
  $recipeOk = $true
  try {
    if ($Docs -eq 'full') { Invoke-DocsRecipeFull } else { Invoke-DocsRecipeSparse }
  } catch {
    $recipeOk = $false
    Say $_.Exception.Message
  }
  if (-not $recipeOk) {
    if (-not $corpusPre) {
      Remove-Item -Recurse -Force "$Root\vendor\ServiceNowDocs" -ErrorAction SilentlyContinue
    }
    Die 'B02' 'the corpus checkout failed' $MSG_NET 1
  }
  # The recipe already carries -c core.longpaths=true; this makes it stick for later git calls in
  # the submodule, where a 197-character path plus a checkout prefix passes 260.
  & git -C "$Root\vendor\ServiceNowDocs" config core.longpaths true 2>$null | Out-Null
  $areas = @(Get-Content "$Root\vendor\docs-areas.txt" | Where-Object { $_.Trim() -ne '' })
  foreach ($area in $areas) {
    if (-not (Test-Path (Join-Path "$Root\vendor\ServiceNowDocs" $area))) {
      Die 'B02' ("area $area missing") 'run ./snowarch docs sync once Node is installed, or re-run .\bootstrap.cmd' 1
    }
  }
  Say ("areas: {0}/{0} present" -f $areas.Length)
  Say $MSG_CITATIONS
  $watch.Stop()
  Step 'B02' 'docs' ("ok ({0} s)" -f [int]$watch.Elapsed.TotalSeconds)
  Record 'B02' 'ok' ([int]$watch.ElapsedMilliseconds)
}

$LocalSettings = "$Root\.claude\settings.local.json"
if (-not (Test-Path $LocalSettings)) {
  # S-05 variant B with no Node: the disable toggle only. No hook — nothing could run it.
  $toggle = [ordered]@{ disabledMcpjsonServers = @($SERVER_KEY) }
  Write-Json $LocalSettings $toggle 3
} else {
  $existing = Get-Content $LocalSettings -Raw
  if (($existing -match '"disabledMcpjsonServers"') -and ($existing -match ('"' + $SERVER_KEY + '"'))) {
    Say 'ok B07: already set'
  } else {
    Die 'B07' '.claude/settings.local.json exists and cannot be merged without Node.js' ('add "disabledMcpjsonServers": ["' + $SERVER_KEY + '"] to it by hand (see docs/INSTALL.md "Design-only without Node"), or install Node 20+ and re-run .\bootstrap.cmd') 1
  }
}
$config = [ordered]@{
  version = 1; mode = 'design-only'; defaultInstance = $null; registration = 'project'
  updatedAt = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
}
Write-Json "$Root\.local\config.json" $config 3
Step 'B07' 'toggles' 'ok'; Record 'B07' 'ok'

$cache = [ordered]@{
  version = 1; at = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ'); writer = 'bootstrap'
  engineVersion = $null; contractSha = $null; mode = 'design-only'
  checks = @(
    [ordered]@{ id = 'B01'; status = 'ok'; detail = 'workspace' },
    [ordered]@{ id = 'B02'; status = 'ok'; detail = 'docs' },
    [ordered]@{ id = 'B07'; status = 'ok'; detail = 'toggles' }
  )
  summary = [ordered]@{ ok = 3; warn = 0; fail = 0 }
}
Write-Json "$Root\.local\doctor-last.json" $cache 5
Step 'B09' 'summary' 'ok'; Record 'B09' 'ok'
Say $MSG_DOCTOR
Say $MSG_MODE
Say $MSG_NEXT
exit 0
