#!/usr/bin/env bash
# The launcher. Two jobs: hand over to Node when it is here, and finish design-only when it is not.
#
# bash 3.2 (macOS ships it) — no associative arrays, no `mapfile`, no `${var,,}`, no `[[ =~ ]]`
# captures, no `curl`/`jq`/`python`/`timeout`. `set -e` is deliberately absent: every failure here
# prints a remedy, and a silent exit is the one thing this file must never do.
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"

# text-begin (generated by scripts/gen-launcher-text.mjs — do not edit)
SERVER_KEY='servicenow'
MSG_NODE_DARWIN='brew install node@22'
MSG_NODE_LINUX='install Node.js from your distribution'\''s package manager, or use nvm'
MSG_NODE_WIN='winget install OpenJS.NodeJS.LTS'
MSG_GIT_DARWIN='xcode-select --install (or: brew install git)'
MSG_GIT_LINUX='install git with your distribution'\''s package manager (apt install git · dnf install git)'
MSG_GIT_WIN='winget install Git.Git'
MSG_CLAUDE='install Claude Code from https://code.claude.com/docs/en/setup, then re-run'
MSG_NET='check your network, or set HTTPS_PROXY / NO_PROXY for your environment, and re-run'
MSG_DNS_FMT='cannot reach %s (DNS) — check your network and re-run'
MSG_UPSTREAM_LOCAL='corpus upstream is local — no probe'
MSG_UPSTREAM_SCHEME_FMT='corpus upstream is %s — not probed (this check speaks HTTPS)'
MSG_TLS='TLS interception detected — set GIT_SSL_CAINFO (or git config http.sslCAInfo) to your corporate CA bundle and re-run; the MCP server needs the same bundle via NODE_EXTRA_CA_CERTS (docs/TROUBLESHOOTING.md)'
MSG_DOCTOR='DOCTOR: unavailable until Node 20+ is installed (design-only is complete)'
MSG_MODE='Mode: design-only'
MSG_NEXT='Next: run `claude` here. You will see one workspace-trust dialog — answer Yes.
      (If you are already inside Claude Code in this folder: exit it and start `claude` again.)
      Add a live instance later with ./snowarch mode live, or /snowarch setup-instance inside Claude.'
MSG_CITATIONS='citations: not verified until Node 20+ is installed'
# text-end

. "$ROOT/tools/snowarch/launcher/docs-recipe.sh"

MODE=design ; DOCS=sparse ; YES=0 ; RESET=0 ; SKIP_CLAUDE=0 ; NODE_ONLY=0
ORIG=("$@")          # kept intact for the hand-over: Node parses its own flags

say() { printf '%s\n' "$*" ; }
step() { printf '[%s/09] %s … %s\n' "$1" "$2" "$3" ; }
die() { say "FAIL $1: $2" ; [ -n "${3:-}" ] && say "Remedy: $3" ; exit "$4" ; }
# Git Bash and MSYS2 report MINGW64_NT / MSYS_NT: a Windows machine running the POSIX launcher.
# Telling that user to `apt install git` — which is what the `*` arm did until ARC-06-S12 — is
# telling them to type something that cannot work on the machine they are sitting at.
platform() { case "$(uname -s)" in Darwin) echo darwin ;; MINGW*|MSYS*|CYGWIN*) echo win32 ;; *) echo linux ;; esac ; }
# The floors, from the generated config: one key per line, which ARC-06-S14 asserts.
floor() { sed -n 's/.*"'"$1"'": *"\([0-9][0-9.]*\)".*/\1/p' "$ROOT/engine.config.json" ; }
# Version compare without `sort -V`, which BSD does not have. Three numeric fields.
ge() { echo "$1 $2" | awk '{split($1,a,".");split($2,b,".");for(i=1;i<=3;i++){x=a[i]+0;y=b[i]+0;if(x>y)exit 0;if(x<y)exit 1}exit 0}' ; }

# One pass, shifting: `--mode live` arrives as two words and `--mode=live` as one, and a second
# scanning loop to catch the pair form was both longer and a place for the two to disagree.
while [ $# -gt 0 ] ; do
  case "$1" in
    --mode) MODE="${2:-}" ; shift ;;      --mode=*) MODE="${1#*=}" ;;
    --docs) DOCS="${2:-}" ; shift ;;      --docs=*) DOCS="${1#*=}" ;;
    --yes) YES=1 ;; --reset) RESET=1 ;; --skip-claude-check) SKIP_CLAUDE=1 ;;
    --from|--instance-file) NODE_ONLY=1 ; shift ;;
    --from=*|--instance-file=*|--json) NODE_ONLY=1 ;;
    --help|-h) say "usage: ./bootstrap.sh [--mode design|live] [--docs sparse|full|skip] [--yes] [--reset]" ; exit 0 ;;
  esac
  shift
done

[ "$(pwd -P)" = "$ROOT" ] || die B00 "not at the repository root" "cd \"$ROOT\" && ./bootstrap.sh" 3

if [ "$RESET" = 1 ] ; then
  rm -f "$ROOT/.local/bootstrap-state.json" "$ROOT/.local/doctor-last.json"
  say "reset: bootstrap state cleared (.local/instances.json and .local/config.json untouched)"
  exit 0
fi

# The hand-over. Everything after this point runs only when Node cannot.
NODE_MAJOR=''
if command -v node >/dev/null 2>&1 ; then
  NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null)"
fi
if [ -n "$NODE_MAJOR" ] && ge "$NODE_MAJOR.0.0" "$(floor node)" ; then
  # Our spawn, so the session variable is SET rather than inherited (ARC-06-S08).
  CLAUDE_PROJECT_DIR="$ROOT" ; export CLAUDE_PROJECT_DIR
  exec node "$ROOT/tools/snowarch/bin/snowarch.mjs" bootstrap ${ORIG[@]+"${ORIG[@]}"}
fi

PLAT="$(platform)"
case "$PLAT" in
  darwin) NODE_REMEDY="$MSG_NODE_DARWIN" ; GIT_REMEDY="$MSG_GIT_DARWIN" ;;
  win32)  NODE_REMEDY="$MSG_NODE_WIN" ; GIT_REMEDY="$MSG_GIT_WIN" ;;
  *)      NODE_REMEDY="$MSG_NODE_LINUX" ; GIT_REMEDY="$MSG_GIT_LINUX" ;;
esac
[ "$NODE_ONLY" = 1 ] && die B00 "that flag needs Node.js 20+" "$NODE_REMEDY" 3
[ "$MODE" = live ] && die B00 "live mode needs Node.js 20+" "$NODE_REMEDY" 3
GIT_V="$(git --version 2>/dev/null | sed -n 's/^git version \([0-9][0-9.]*\).*/\1/p')"
[ -n "$GIT_V" ] || die B00 "git not found" "$GIT_REMEDY" 3
ge "$GIT_V" "$(floor git)" || die B00 "git $GIT_V found, >= $(floor git) required" "$GIT_REMEDY" 3
say "ok B00 git: $GIT_V"
if [ "$SKIP_CLAUDE" = 1 ] ; then
  say "WARN B00: Claude Code check skipped (--skip-claude-check)"
else
  CLAUDE_V="$(claude --version 2>/dev/null | sed -n 's/^\([0-9][0-9.]*\).*/\1/p')"
  [ -n "$CLAUDE_V" ] || die B00 "Claude Code not found on PATH" "$MSG_CLAUDE" 3
  ge "$CLAUDE_V" "$(floor claudeCode)" || die B00 "Claude Code $CLAUDE_V found, >= $(floor claudeCode) required" "$MSG_CLAUDE" 3
  say "ok B00 claudeCode: $CLAUDE_V"
fi
FREE_KB="$(df -Pk "$ROOT" | awk 'NR==2{print $4}')"
[ "$FREE_KB" -ge 1048576 ] 2>/dev/null || die B00 "less than 1 GiB free" "free up space on $ROOT" 3
say "ok B00 disk: $((FREE_KB/1048576)) GB free"
# `-h` is deliberately absent: with it, the pattern `HEAD` matches no head ref, `--exit-code`
# returns 2, and git says nothing — so a probe that reads only stderr called that "reachable"
# and one that reads only the exit code called it "unreachable". Both were reading a flag bug.
# The rule now: the EXIT CODE decides, stderr only chooses which sentence explains it.
# ARC-09-C29: probe the host THIS RUN contacts — the corpus remote, which B02 fetches. A bootstrap
# never contacts the product repository (`upgrade` uses the checkout's own `origin`), so probing it
# asked about one host and said nothing about another. These arms are `corpusProbe()` from
# `tools/snowarch/lib/probe-net.mjs` in shell; its comment carries the reasoning.
UPSTREAM="$(sed -n 's/.*"upstream": *"\([^"]*\)".*/\1/p' "$ROOT/engine.config.json" | head -n 1)"
UP_REST="${UPSTREAM#*://}" ; UP_HOST="${UP_REST%%[/:]*}" ; UP_SCHEME="${UPSTREAM%%://*}"
case "$UPSTREAM" in
  http://*|https://*)
    NET="$(GIT_TERMINAL_PROMPT=0 git -c http.lowSpeedLimit=1000 -c http.lowSpeedTime=20 \
      ls-remote --exit-code "$UPSTREAM" HEAD 2>&1 >/dev/null)" || NET_RC=$?
    if [ -n "${NET_RC:-}" ] ; then
      case "$NET" in
        *"ould not resolve host"*) die B00 "$(printf "$MSG_DNS_FMT" "$UP_HOST")" "$MSG_NET" 3 ;;
        *"SSL certificate problem"*) die B00 "$MSG_TLS" "$MSG_NET" 3 ;;
        *) die B00 "cannot reach $UP_HOST" "$MSG_NET" 3 ;;
      esac
    fi
    say "ok B00 network: $UP_HOST reachable" ;;
  # `file://` BEFORE the scheme arm, or a local upstream is reported as an unspeakable remote —
  # which is what the first version did, and the launcher test said so in one run.
  file://*) say "ok B00 network: $MSG_UPSTREAM_LOCAL" ;;
  # Remote but unspeakable to this probe — NOT the same claim as local, so not the same sentence.
  *://*) say "ok B00 network: $(printf "$MSG_UPSTREAM_SCHEME_FMT" "$UP_SCHEME")" ;;
  *) say "ok B00 network: $MSG_UPSTREAM_LOCAL" ;;
esac
say "ok B00 node: note: Node.js not found — design-only only; live mode needs Node 20+ ($NODE_REMEDY)"
step B00 preflight ok
if [ "$YES" != 1 ] ; then
  DOCS_NOTE=''
  # The area count belongs to a checkout that will happen; printing "skip (19 areas)" describes a
  # corpus nobody is fetching.
  [ "$DOCS" = skip ] || DOCS_NOTE=" ($(grep -c . "$ROOT/vendor/docs-areas.txt" 2>/dev/null || echo 0) areas)"
  say "Plan: Mode design-only (fixed — Node.js 20+ not found) · Docs $DOCS$DOCS_NOTE"
  say "Enter = run · d = docs full · s = docs skip · q = quit"
  read -r answer
  case "$answer" in d|D) DOCS=full ;; s|S) DOCS=skip ;; q|Q) exit 0 ;; esac
fi

write_state() {
  mkdir -p "$ROOT/.local" && chmod 700 "$ROOT/.local" 2>/dev/null
  cat > "$ROOT/.local/bootstrap-state.json" <<STATE
{ "version": 1, "product": "snowarch", "mode": "design-only",
  "docs": { "mode": "$DOCS", "pin": "$(sed -n 's/.*"pin": *"\([0-9a-f]*\)".*/\1/p' "$ROOT/engine.config.json")" },
  "node": { "present": false, "version": null },
  "writer": "bash", "platform": "$PLAT",
  "registration": "project", "registrationReason": "default", "hooksDisabledByBootstrap": false,
  "startedAt": "$STARTED", "updatedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "steps": {$1} }
STATE
}
STARTED="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
STEPS=''
# `$3` is the measured milliseconds, when the step measured itself. `inputsHash` stays null on
# purpose — bash cannot compute the repository's input hashes, so the launcher TIMES a step but
# never caches one.
record() { STEPS="$STEPS${STEPS:+,}
    \"$1\": { \"status\": \"$2\", \"inputsHash\": null, \"finishedAt\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\", \"durationMs\": ${3:-0} }" ; write_state "$STEPS" ; }
record B00 ok
git diff --quiet HEAD -- .mcp.json .claude/settings.json 2>/dev/null || \
  die B01 ".mcp.json or .claude/settings.json differs from the committed version" \
    "run: git checkout -- .mcp.json   (never edit this file; per-machine values belong in .claude/settings.local.json)" 1
step B01 workspace ok ; record B01 ok
if [ "$DOCS" = skip ] ; then
  step B02 docs "skipped (--docs skip) — the doctor will report the corpus as FAIL until you run ./snowarch docs sync"
  record B02 skipped
else
  T0="$(date +%s)"
  # Whether the corpus was here BEFORE this run decides what a failure is allowed to delete. The
  # recipe's first step is `git clone … vendor/ServiceNowDocs`, and a clone refuses a directory that
  # exists and is not empty — so a run that failed halfway and left the directory behind made
  # MSG_NET's "re-run" false: the re-run died on "already exists and is not an empty directory"
  # instead of finishing the job. Bootstrap therefore removes a directory IT CREATED in this run,
  # and never one that was already there, whatever state it is in — someone else's checkout is not
  # ours to delete.
  CORPUS_PRE=0
  [ -d "$ROOT/vendor/ServiceNowDocs" ] && CORPUS_PRE=1
  if [ "$DOCS" = full ] ; then docs_recipe_full ; else docs_recipe_sparse ; fi || {
    [ "$CORPUS_PRE" = 1 ] || [ -z "$ROOT" ] || rm -rf "$ROOT/vendor/ServiceNowDocs"
    die B02 "the corpus checkout failed" "$MSG_NET" 1
  }
  MISSING=''
  while read -r area ; do
    [ -n "$area" ] || continue
    [ -d "$ROOT/vendor/ServiceNowDocs/$area" ] || MISSING="$area"
  done < "$ROOT/vendor/docs-areas.txt"
  [ -z "$MISSING" ] || die B02 "area $MISSING missing" \
    "run ./snowarch docs sync once Node is installed, or re-run ./bootstrap.sh" 1
  PRESENT="$(grep -c . "$ROOT/vendor/docs-areas.txt")"
  say "areas: $PRESENT/$PRESENT present"
  say "$MSG_CITATIONS"
  B02_S=$(( $(date +%s) - T0 ))
  step B02 docs "ok ($B02_S s)" ; record B02 ok $(( B02_S * 1000 ))
fi
LOCAL_SETTINGS="$ROOT/.claude/settings.local.json"
if [ ! -f "$LOCAL_SETTINGS" ] ; then
  # S-05 variant B with no Node: the disable toggle only. No hook, because nothing could run it.
  printf '{\n  "disabledMcpjsonServers": [\n    "%s"\n  ]\n}\n' "$SERVER_KEY" > "$LOCAL_SETTINGS"
elif grep -q '"disabledMcpjsonServers"' "$LOCAL_SETTINGS" && grep -q "\"$SERVER_KEY\"" "$LOCAL_SETTINGS" ; then
  say "ok B07: already set"
else
  die B07 ".claude/settings.local.json exists and cannot be merged without Node.js" \
    "add \"disabledMcpjsonServers\": [\"$SERVER_KEY\"] to it by hand (see docs/INSTALL.md \"Design-only without Node\"), or install Node 20+ and re-run ./bootstrap.sh" 1
fi
cat > "$ROOT/.local/config.json" <<CONFIG
{ "version": 1, "mode": "design-only", "defaultInstance": null,
  "registration": "project", "updatedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)" }
CONFIG
step B07 toggles ok ; record B07 ok
cat > "$ROOT/.local/doctor-last.json" <<CACHE
{ "version": 1, "at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)", "writer": "bootstrap",
  "engineVersion": null, "contractSha": null, "mode": "design-only",
  "checks": [ { "id": "B01", "status": "ok", "detail": "workspace" },
              { "id": "B02", "status": "ok", "detail": "docs" },
              { "id": "B07", "status": "ok", "detail": "toggles" } ],
  "summary": { "ok": 3, "warn": 0, "fail": 0 } }
CACHE
chmod 600 "$ROOT/.local/doctor-last.json" 2>/dev/null
step B09 summary ok ; record B09 ok
say "$MSG_DOCTOR"
say "$MSG_MODE"
say "$MSG_NEXT"
exit 0
