import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * `scripts/gen-roster.mjs`, driven through the CLI against a tree built per case.
 *
 * The tree is built in a temp directory rather than committed under `tests/fixtures/`, because
 * half of these cases need a BROKEN skill — no `**Fires:**` line, a Fires line nobody can
 * classify — and a broken `SKILL.md` inside the repository is a file every other lint then has to
 * be taught to skip. Built here, each case says in one place exactly what it is testing.
 */
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CLI = join(root, 'scripts', 'gen-roster.mjs');

const SKILLS = [
  ['alpha-specialist', 'gateway', 'Phase 1 Step 5 (before any builder dispatch).', '2.0.0'],
  ['beta-writer', 'builder', 'On dispatch from the Chief Architect after routing approval.', '1.0.0'],
  ['gamma-reviewer', 'post-build consult', 'Post-build per taxonomy §6.2, and on demand.', '1.1.0'],
];

function tree(mutate = () => {}) {
  const dir = mkdtempSync(join(tmpdir(), 'roster-'));
  const write = (rel, body) => {
    mkdirSync(join(dir, dirname(rel)), { recursive: true });
    writeFileSync(join(dir, rel), body);
  };
  for (const [name, , fires, version] of SKILLS) {
    write(`.claude/skills/${name}/SKILL.md`, [
      '---', `name: ${name}`, `description: Does ${name} things. And more besides.`,
      'metadata:', `  version: ${version}`, '---', '', '## Triggers', '',
      `**Fires:** ${fires}`, '',
    ].join('\n'));
  }
  write('.claude/agents/beta-writer.md', [
    '---', 'name: beta-writer',
    'description: Write the beta artefact from a spec. Returns it, and a manifest.',
    'tools: Read, Write', 'model: inherit', 'skills:', '  - beta-writer', '---', '', '# Beta', '',
  ].join('\n'));
  write('engine.config.json', `${JSON.stringify({ roster: { skills: 3, agents: 1 } }, null, 2)}\n`);
  write('docs/ARCHITECTURE.md', [
    '# Fixture', '',
    '<!-- ROSTER:BEGIN (generated by scripts/gen-roster.mjs — do not edit) -->',
    '<!-- ROSTER:END -->', '', 'Tail text that must survive.', '',
  ].join('\n'));
  mutate({ dir, write });
  return dir;
}

function run(dir, args = []) {
  try {
    return { code: 0, out: execFileSync(process.execPath, [CLI, '--root', dir, ...args], { encoding: 'utf8', stdio: 'pipe' }) };
  } catch (e) {
    return { code: e.status ?? -1, out: e.stdout ?? '', err: e.stderr ?? '' };
  }
}

const architecture = (dir) => readFileSync(join(dir, 'docs', 'ARCHITECTURE.md'), 'utf8');
const cleanup = (dir) => rmSync(dir, { recursive: true, force: true });

test('the generated block is exactly this, and the text around it survives', () => {
  const dir = tree();
  try {
    assert.equal(run(dir).code, 0);
    const doc = architecture(dir);
    // Written out in full rather than counted: the block IS the deliverable, and a snapshot that
    // only asserted "three rows" would let the columns, the summary wording or the sort order
    // change without a word of review.
    assert.equal(doc, [
      '# Fixture', '',
      '<!-- ROSTER:BEGIN (generated by scripts/gen-roster.mjs — do not edit) -->',
      '',
      '**3 specialist personas · 3 skills · 1 sub-agents**',
      '',
      '### Skills',
      '',
      '| Skill | Fires as | Sub-agent | Version |',
      '|---|---|---|---|',
      '| `alpha-specialist` | gateway | — | 2.0.0 |',
      '| `beta-writer` | builder | yes | 1.0.0 |',
      '| `gamma-reviewer` | post-build consult | — | 1.1.0 |',
      '',
      '### Sub-agents',
      '',
      '| Agent | Preloads | What it does |',
      '|---|---|---|',
      '| `beta-writer` | `beta-writer` | Write the beta artefact from a spec. |',
      '',
      '### Utility skills',
      '',
      '| Skill | Version |',
      '|---|---|',
      '',
      '*None yet — ARC-02-S11 adds `snowarch`.*',
      '',
      '<!-- ROSTER:END -->', '', 'Tail text that must survive.', '',
    ].join('\n'));
  } finally { cleanup(dir); }
});

test('criterion 3 — the agent cell is the first sentence, not the description', () => {
  const dir = tree();
  try {
    run(dir);
    const doc = architecture(dir);
    assert.match(doc, /\| Write the beta artefact from a spec\. \|/);
    assert.ok(!doc.includes('Returns it, and a manifest'), 'the second sentence reached the table');
  } finally { cleanup(dir); }
});

test('ruling 2 — the utility table is generated while the config lists none', () => {
  // So ARC-02-S11 adds `snowarch` to `engine.config.json` and changes no generator code.
  const dir = tree();
  try {
    run(dir);
    assert.match(architecture(dir), /### Utility skills\n\n\| Skill \| Version \|/);
  } finally { cleanup(dir); }
});

test('criterion 1 — a second run changes nothing, and --check exits 0', () => {
  const dir = tree();
  try {
    run(dir);
    const first = architecture(dir);
    assert.equal(run(dir).code, 0);
    assert.equal(architecture(dir), first);
    const check = run(dir, ['--check']);
    assert.equal(check.code, 0);
    assert.match(check.out, /roster block is current \(3 skills, 1 agents, 0 utility\)/);
  } finally { cleanup(dir); }
});

test('criterion 2 — a new skill makes --check exit 1 with the row and the count', () => {
  const dir = tree();
  try {
    run(dir);
    mkdirSync(join(dir, '.claude/skills/zz-dummy'), { recursive: true });
    writeFileSync(join(dir, '.claude/skills/zz-dummy/SKILL.md'),
      ['---', 'name: zz-dummy', 'description: Temporary.', 'metadata:', '  version: 0.0.1', '---',
        '', '## Triggers', '', '**Fires:** On demand.', ''].join('\n'));
    const r = run(dir, ['--check']);
    assert.equal(r.code, 1);
    assert.match(r.out, /^\+\| `zz-dummy` \| on demand \| — \| 0\.0\.1 \|$/m);
    assert.match(r.out, /gen-roster: roster\.skills 3 ≠ 4 found/);
    assert.match(r.out, /run `node scripts\/gen-roster\.mjs` and commit the result/);
  } finally { cleanup(dir); }
});

test('criterion 5 — a CRLF checkout is not a diff', () => {
  // The Windows cell checks out with `core.autocrlf`, and a comparison on raw bytes would report
  // every line of the block as changed on a file nobody touched.
  const dir = tree();
  try {
    run(dir);
    const p = join(dir, 'docs', 'ARCHITECTURE.md');
    writeFileSync(p, readFileSync(p, 'utf8').replace(/\n/g, '\r\n'));
    assert.equal(run(dir, ['--check']).code, 0);
  } finally { cleanup(dir); }
});

test('ruling 1 — a missing Fires line is a failure, never "unknown"', () => {
  const dir = tree(({ write }) => {
    write('.claude/skills/alpha-specialist/SKILL.md',
      ['---', 'name: alpha-specialist', 'description: No triggers section at all.',
        'metadata:', '  version: 2.0.0', '---', '', '# Alpha', ''].join('\n'));
  });
  try {
    const r = run(dir);
    // Exit 2, not 1: the roster could not be built, which is a different thing from a stale block.
    assert.equal(r.code, 2);
    assert.match(r.err, /alpha-specialist\/SKILL\.md: no "\*\*Fires:\*\*" line/);
    assert.ok(!architecture(dir).includes('unknown'), 'a placeholder reached the document');
  } finally { cleanup(dir); }
});

test('a Fires line nobody can classify fails too, and prints the line', () => {
  const dir = tree(({ write }) => {
    write('.claude/skills/alpha-specialist/SKILL.md',
      ['---', 'name: alpha-specialist', 'description: Unclassifiable.', 'metadata:',
        '  version: 2.0.0', '---', '', '## Triggers', '', '**Fires:** Whenever it feels like it.', ''].join('\n'));
  });
  try {
    const r = run(dir);
    assert.equal(r.code, 2);
    assert.match(r.err, /matches no classification — "Whenever it feels like it\."/);
    assert.match(r.err, /It is never guessed/);
  } finally { cleanup(dir); }
});

test('the two reference declarations must agree', () => {
  // `REFERENCE_SKILLS` and the Fires line both say which skills are reference companions. One
  // would be enough to print the summary; two that must agree is what stops a reworded line from
  // quietly moving a skill into the persona count.
  const dir = tree(({ write }) => {
    write('.claude/skills/gamma-reviewer/SKILL.md',
      ['---', 'name: gamma-reviewer', 'description: Reworded.', 'metadata:', '  version: 1.1.0',
        '---', '', '## Triggers', '', '**Fires:** On demand, to ground the builder.', ''].join('\n'));
  });
  try {
    const r = run(dir);
    assert.equal(r.code, 2);
    assert.match(r.err, /classified "reference".*REFERENCE_SKILLS does not list it/s);
  } finally { cleanup(dir); }
});

test('an agent that preloads a skill that is not there, and one with no persona', () => {
  const dir = tree(({ write }) => {
    write('.claude/agents/beta-writer.md',
      ['---', 'name: beta-writer', 'description: Missing its own persona.', 'tools: Read',
        'model: inherit', 'skills:', '  - nope', '---', '', '# Beta', ''].join('\n'));
  });
  try {
    const r = run(dir);
    assert.equal(r.code, 1);
    assert.match(r.out, /preloads "nope", which is not a skill/);
    assert.match(r.out, /does not preload its own persona skill "beta-writer"/);
  } finally { cleanup(dir); }
});

test('--json is the shape ARC-08-S02 consumes', () => {
  const dir = tree();
  try {
    const r = run(dir, ['--json']);
    assert.equal(r.code, 0);
    const doc = JSON.parse(r.out);
    assert.deepEqual(doc.skills.map((s) => s.name), ['alpha-specialist', 'beta-writer', 'gamma-reviewer']);
    assert.deepEqual(doc.agents.map((a) => a.name), ['beta-writer']);
    assert.deepEqual(doc.utility, []);
    assert.deepEqual(doc.problems, []);
    assert.equal(doc.skills[0].firesAs, 'gateway');
  } finally { cleanup(dir); }
});

test('a missing marker block cannot run', () => {
  const dir = tree(({ write }) => write('docs/ARCHITECTURE.md', '# Fixture\n\nNo markers here.\n'));
  try {
    const r = run(dir);
    assert.equal(r.code, 2);
    assert.match(r.err, /has no ROSTER:BEGIN \/ ROSTER:END block — add the two markers first/);
  } finally { cleanup(dir); }
});
