# The corpus recipe for the Node-free launcher (ARC-06-S10 sources this file).
#
# The two function BODIES are GENERATED by `scripts/gen-docs-recipe.mjs` from
# `tools/snowarch/lib/docs/recipe-block.mjs`, which is the same function `./snowarch docs sync`
# runs and the same one `docs/ARCHITECTURE.md` publishes. Do not edit between the markers: the
# recipe embeds the docs pin, the bump moves it, and a hand-edited copy is a copy that drifts.
#
# POSIX sh — no bashisms, because `bootstrap.sh` targets bash 3.2 and Git Bash alike.

docs_recipe_sparse() {
# recipe-begin sparse
  git clone --filter=blob:none --no-checkout --depth 1 --sparse --branch australia https://github.com/ServiceNow/ServiceNowDocs.git vendor/ServiceNowDocs && \
  git -C vendor/ServiceNowDocs sparse-checkout set --cone markdown/api-reference markdown/application-development markdown/build-workflows markdown/core-business-suite markdown/customer-service-management markdown/employee-service-management markdown/governance-risk-compliance markdown/integrate-applications markdown/intelligent-experiences markdown/it-asset-management markdown/it-business-management markdown/it-operations-management markdown/it-service-management markdown/now-intelligence markdown/now-platform markdown/platform-administration markdown/platform-security markdown/platform-user-interface markdown/servicenow-platform legal && \
  git -C vendor/ServiceNowDocs fetch --depth 1 origin 11b39be17307dd4b21df15a54e8011ae68f64dba && \
  git -C vendor/ServiceNowDocs checkout --detach 11b39be17307dd4b21df15a54e8011ae68f64dba && \
  { git submodule absorbgitdirs vendor/ServiceNowDocs || true ; } && \
  { git submodule init -- vendor/ServiceNowDocs || true ; } && \
  echo "docs: ServiceNow product documentation © 2026 ServiceNow, Apache-2.0 — vendor/ServiceNowDocs/LICENSE"
  # if a step fails with a network error, re-run: a failed run leaves nothing behind, and a re-run of a checkout fetches only what is missing
# recipe-end
}

docs_recipe_full() {
# recipe-begin full
  git clone --filter=blob:none --no-checkout --depth 1 --sparse --branch australia https://github.com/ServiceNow/ServiceNowDocs.git vendor/ServiceNowDocs && \
  git -C vendor/ServiceNowDocs sparse-checkout disable && \
  git -C vendor/ServiceNowDocs fetch --depth 1 origin 11b39be17307dd4b21df15a54e8011ae68f64dba && \
  git -C vendor/ServiceNowDocs checkout --detach 11b39be17307dd4b21df15a54e8011ae68f64dba && \
  { git submodule absorbgitdirs vendor/ServiceNowDocs || true ; } && \
  { git submodule init -- vendor/ServiceNowDocs || true ; } && \
  echo "docs: ServiceNow product documentation © 2026 ServiceNow, Apache-2.0 — vendor/ServiceNowDocs/LICENSE"
  # if a step fails with a network error, re-run: a failed run leaves nothing behind, and a re-run of a checkout fetches only what is missing
# recipe-end
}
