# The corpus recipe for the Node-free Windows launcher (ARC-06-S11 dot-sources this file).
#
# The two function BODIES are GENERATED by `scripts/gen-docs-recipe.mjs` from
# `tools/snowarch/lib/docs/recipe-block.mjs`, which is the same function `./snowarch docs sync`
# runs. Do not edit between the markers.
#
# The lines are the Windows form of the recipe, so they carry `-c core.longpaths=true`: a corpus
# path here reaches 197 characters, and a temp-directory prefix takes the total past 260.

function Invoke-DocsRecipeSparse {
# recipe-begin sparse
  if (-not (Test-Path "vendor/ServiceNowDocs/.git")) {
    git -c core.longpaths=true clone --filter=blob:none --no-checkout --depth 1 --sparse --branch australia https://github.com/ServiceNow/ServiceNowDocs.git vendor/ServiceNowDocs
    if ($LASTEXITCODE -ne 0) { throw "corpus: clone failed" }
  }
  git -c core.longpaths=true -C vendor/ServiceNowDocs sparse-checkout set --cone markdown/api-reference markdown/application-development markdown/build-workflows markdown/core-business-suite markdown/customer-service-management markdown/employee-service-management markdown/governance-risk-compliance markdown/integrate-applications markdown/intelligent-experiences markdown/it-asset-management markdown/it-business-management markdown/it-operations-management markdown/it-service-management markdown/now-intelligence markdown/now-platform markdown/platform-administration markdown/platform-security markdown/platform-user-interface markdown/servicenow-platform legal
  if ($LASTEXITCODE -ne 0) { throw "corpus: sparse-checkout set failed" }
  git -c core.longpaths=true -C vendor/ServiceNowDocs fetch --depth 1 origin 11b39be17307dd4b21df15a54e8011ae68f64dba
  if ($LASTEXITCODE -ne 0) { throw "corpus: fetch failed" }
  git -c core.longpaths=true -C vendor/ServiceNowDocs checkout --detach 11b39be17307dd4b21df15a54e8011ae68f64dba
  if ($LASTEXITCODE -ne 0) { throw "corpus: checkout failed" }
  git -c core.longpaths=true submodule absorbgitdirs vendor/ServiceNowDocs
  git -c core.longpaths=true submodule init -- vendor/ServiceNowDocs
  git -c core.longpaths=true -C vendor/ServiceNowDocs config core.longpaths true
  if ($LASTEXITCODE -ne 0) { throw "corpus: config failed" }
  echo "docs: ServiceNow product documentation © 2026 ServiceNow, Apache-2.0 — vendor/ServiceNowDocs/LICENSE"
  # if a step fails with a network error, re-run: a failed run leaves nothing behind, and a re-run of a checkout fetches only what is missing
# recipe-end
}

function Invoke-DocsRecipeFull {
# recipe-begin full
  if (-not (Test-Path "vendor/ServiceNowDocs/.git")) {
    git -c core.longpaths=true clone --filter=blob:none --no-checkout --depth 1 --sparse --branch australia https://github.com/ServiceNow/ServiceNowDocs.git vendor/ServiceNowDocs
    if ($LASTEXITCODE -ne 0) { throw "corpus: clone failed" }
  }
  git -c core.longpaths=true -C vendor/ServiceNowDocs sparse-checkout disable
  if ($LASTEXITCODE -ne 0) { throw "corpus: sparse-checkout disable failed" }
  git -c core.longpaths=true -C vendor/ServiceNowDocs fetch --depth 1 origin 11b39be17307dd4b21df15a54e8011ae68f64dba
  if ($LASTEXITCODE -ne 0) { throw "corpus: fetch failed" }
  git -c core.longpaths=true -C vendor/ServiceNowDocs checkout --detach 11b39be17307dd4b21df15a54e8011ae68f64dba
  if ($LASTEXITCODE -ne 0) { throw "corpus: checkout failed" }
  git -c core.longpaths=true submodule absorbgitdirs vendor/ServiceNowDocs
  git -c core.longpaths=true submodule init -- vendor/ServiceNowDocs
  git -c core.longpaths=true -C vendor/ServiceNowDocs config core.longpaths true
  if ($LASTEXITCODE -ne 0) { throw "corpus: config failed" }
  echo "docs: ServiceNow product documentation © 2026 ServiceNow, Apache-2.0 — vendor/ServiceNowDocs/LICENSE"
  # if a step fails with a network error, re-run: a failed run leaves nothing behind, and a re-run of a checkout fetches only what is missing
# recipe-end
}
