#!/usr/bin/env node
// ARC-06-S09 — `tools/snowarch/lib/text.json`, generated from `text.mjs`.
//
// The Node-free launchers (S10/S11) print the same closing block, and they cannot import a module.
// So the strings are exported as data and their parity test reads this file — the same shape as
// ARC-06-S04's `remedies.json`, and for the same reason: one definition, three programs.
import { readFileSync, writeFileSync, writeSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const argv = process.argv.slice(2);
const rootArg = argv.indexOf('--root');
const root = rootArg === -1
  ? resolve(dirname(fileURLToPath(import.meta.url)), '..')
  : resolve(argv[rootArg + 1]);
const check = argv.includes('--check');

const TARGET = 'tools/snowarch/lib/text.json';
const { exportable } = await import(
  pathToFileURL(join(root, 'tools/snowarch/lib/text.mjs')).href);
const config = JSON.parse(readFileSync(join(root, 'engine.config.json'), 'utf8'));

const next = `${JSON.stringify({
  $comment: 'GENERATED by scripts/gen-text.mjs from tools/snowarch/lib/text.mjs — do not edit. '
    + 'The Node-free launchers print these strings; the parity test reads this file.',
  ...exportable({ serverKey: config.mcp.serverKey }),
}, null, 2)}\n`;

const path = join(root, TARGET);
let current = null;
try { current = readFileSync(path, 'utf8'); } catch { /* first run */ }

if (check) {
  if (current !== next) {
    writeSync(2, `gen-text: ${TARGET} is STALE — run node scripts/gen-text.mjs\n`);
    process.exit(1);
  }
  writeSync(1, `gen-text: ${TARGET} is current\n`);
  process.exit(0);
}
writeFileSync(path, next);
writeSync(1, `gen-text: ${current === next ? 'no change to' : 'wrote'} ${TARGET}\n`);
