#!/usr/bin/env node
/**
 * Generate the roster block in `docs/ARCHITECTURE.md` from the directory listing.
 *
 * Five documents used to disagree about the roster — 8 or 9 agents, 12 / 22 / 24 / 25 / 27 skills
 * (`00` §3.8, P-12). Every one of those numbers was written by hand and was true when written.
 * This replaces the counting with a listing: the block between the markers is produced from
 * every `.claude/skills/<name>/SKILL.md` and `.claude/agents/<name>.md`, and `--check` fails CI
 * if the committed text is not what those files produce.
 *
 * Usage:
 *   node scripts/gen-roster.mjs            rewrite the block in docs/ARCHITECTURE.md
 *   node scripts/gen-roster.mjs --check    exit 1 with a unified diff if it is stale
 *   node scripts/gen-roster.mjs --json     print the roster as data (ARC-08-S02's doctor check)
 *
 * Exit 0 written/current · 1 stale or inconsistent · 2 cannot run.
 *
 * Stdlib only. It runs in `npm run lint` on every CI cell including Windows, where the comparison
 * is done on LF-normalised text so a checkout with `core.autocrlf` does not read as a diff.
 */
import { existsSync, readFileSync, writeFileSync, writeSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// `fileURLToPath`, never `new URL(...).pathname` — the latter is `/C:/…` on Windows.
import { unifiedDiff } from './lib/diff.mjs';
// The listing itself lives in `lib/roster.mjs`, because the doctor's E-17/E-18 read the same
// roster (ARC-08-S02) and a second reading would be a second definition of it (P-12).
import { collectRoster, RosterError } from './lib/roster.mjs';

// `--root <dir>` points every read at a fixture tree; without it, the repository this script
// lives in. The tests drive the CLI rather than the functions, because the exit code and the
// diff text are the product here — a test that called `render()` would not see either.
const argv = process.argv.slice(2);
const rootArg = argv.indexOf('--root');
const ROOT = resolve(rootArg === -1 ? resolve(dirname(fileURLToPath(import.meta.url)), '..') : argv[rootArg + 1]);
const TARGET = join(ROOT, 'docs', 'ARCHITECTURE.md');
const BEGIN = '<!-- ROSTER:BEGIN (generated by scripts/gen-roster.mjs — do not edit) -->';
const END = '<!-- ROSTER:END -->';

const fail = (message) => { writeSync(2, `gen-roster: ${message}\n`); process.exit(2); };
const posix = (p) => p.split('\\').join('/');
const lf = (s) => s.replace(/\r\n/g, '\n');

function read(rel) {
  const p = join(ROOT, rel);
  if (!existsSync(p)) fail(`${posix(rel)} is missing`);
  return readFileSync(p, 'utf8');
}

const cell = (s) => String(s).replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();

function render({ skills, agents, utility }, firstSentence) {
  const roster = skills.filter((s) => !utility.has(s.dir));
  const personas = roster.filter((s) => !s.isReference);
  // An agent's PERSONA, not everything it preloads. `now-assist-specialist` also preloads
  // `now-assist-genai`, and the companion having a sub-agent is precisely what it does not have —
  // it is reference knowledge loaded alongside a builder. The preload is still visible in the
  // sub-agent table's own column, where it says what it is.
  const withAgent = new Set(agents.map((a) => a.name));
  const companions = roster.filter((s) => s.isReference).map((s) => s.name).join(', ');

  const out = [BEGIN, ''];
  // Every number here is counted, never typed. The parenthetical names the companion so a reader
  // can see why the two totals differ by one.
  out.push(`**${personas.length} specialist personas · ${roster.length} skills`
    + `${companions ? ` (incl. ${companions} reference companion)` : ''}`
    + ` · ${agents.length} sub-agents**`, '');

  out.push('### Skills', '', '| Skill | Fires as | Sub-agent | Version |', '|---|---|---|---|');
  for (const s of roster) {
    out.push(`| \`${cell(s.name)}\` | ${cell(s.firesAs)} | ${withAgent.has(s.name) ? 'yes' : '—'} `
      + `| ${cell(s.version)} |`);
  }

  out.push('', '### Sub-agents', '', '| Agent | Preloads | What it does |', '|---|---|---|');
  for (const a of agents) {
    const preloads = a.skills.map((s) => `\`${cell(s)}\``).join(', ') || '—';
    out.push(`| \`${cell(a.name)}\` | ${preloads} | ${cell(firstSentence(a.description))} |`);
  }

  out.push('', '### Utility skills', '', '| Skill | Version |', '|---|---|');
  const utilityRows = skills.filter((s) => utility.has(s.dir));
  for (const s of utilityRows) out.push(`| \`${cell(s.name)}\` | ${cell(s.version)} |`);
  if (utilityRows.length === 0) {
    // The heading and the empty table are generated while `roster.utility` is empty, so
    // ARC-02-S11 adds `snowarch` to the config and changes no generator code (ruling 2).
    out.push('', '*None yet — ARC-02-S11 adds `snowarch`.*');
  }

  out.push('', END);
  return out.join('\n');
}


async function main() {
  const { firstSentence } = await import('./lib/text.mjs');

  // One call, one listing. `RosterError` is the library's way of saying the tree cannot be read;
  // here that is exit 2, and in the doctor the same message becomes a FAIL line.
  let model;
  try {
    model = collectRoster(ROOT);
  } catch (e) {
    if (e instanceof RosterError) fail(e.message);
    throw e;
  }
  const { agents, utility, rosterSkills, problems } = model;

  if (argv.includes('--json')) {
    writeSync(1, `${JSON.stringify(
      { skills: model.skills, agents, utility: [...utility], problems }, null, 2)}\n`);
    process.exit(problems.length > 0 ? 1 : 0);
  }

  const block = render(model, firstSentence);
  const doc = read('docs/ARCHITECTURE.md');
  const start = doc.indexOf(BEGIN);
  const stop = doc.indexOf(END);
  if (start === -1 || stop === -1 || stop < start) {
    fail('docs/ARCHITECTURE.md has no ROSTER:BEGIN / ROSTER:END block — add the two markers first');
  }
  const current = doc.slice(start, stop + END.length);
  const next = doc.slice(0, start) + block + doc.slice(stop + END.length);

  if (argv.includes('--check')) {
    // LF-normalised on both sides: the Windows cell checks out with CRLF and the file is
    // otherwise identical, which is not a diff anybody can act on (criterion 5).
    const stale = lf(current) !== lf(block);
    if (stale) writeSync(1, `${unifiedDiff(lf(current), lf(block), 'docs/ARCHITECTURE.md')}\n`);
    for (const p of problems) writeSync(1, `gen-roster: ${p}\n`);
    if (stale || problems.length > 0) {
      writeSync(1, 'gen-roster: run `node scripts/gen-roster.mjs` and commit the result\n');
      process.exit(1);
    }
    writeSync(1, `gen-roster: docs/ARCHITECTURE.md roster block is current `
      + `(${rosterSkills.length} skills, ${agents.length} agents, ${utility.size} utility)\n`);
    process.exit(0);
  }

  for (const p of problems) writeSync(1, `gen-roster: ${p}\n`);
  if (problems.length > 0) process.exit(1);
  writeFileSync(TARGET, next);
  writeSync(1, `gen-roster: wrote docs/ARCHITECTURE.md `
    + `(${rosterSkills.length} skills, ${agents.length} agents, ${utility.size} utility)\n`);
}

main();
