#!/usr/bin/env node
/**
 * Generate the roster block in `docs/ARCHITECTURE.md` from the directory listing.
 *
 * Five documents used to disagree about the roster — 8 or 9 agents, 12 / 22 / 24 / 25 / 27 skills
 * (`00` §3.8, P-12). Every one of those numbers was written by hand and was true when written.
 * This replaces the counting with a listing: the block between the markers is produced from
 * every `.claude/skills/<name>/SKILL.md` and `.claude/agents/<name>.md`, and `--check` fails CI
 * if the committed text is not what those files produce.
 *
 * Usage:
 *   node scripts/gen-roster.mjs            rewrite the block in docs/ARCHITECTURE.md
 *   node scripts/gen-roster.mjs --check    exit 1 with a unified diff if it is stale
 *   node scripts/gen-roster.mjs --json     print the roster as data (ARC-08-S02's doctor check)
 *
 * Exit 0 written/current · 1 stale or inconsistent · 2 cannot run.
 *
 * Stdlib only. It runs in `npm run lint` on every CI cell including Windows, where the comparison
 * is done on LF-normalised text so a checkout with `core.autocrlf` does not read as a diff.
 */
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// `fileURLToPath`, never `new URL(...).pathname` — the latter is `/C:/…` on Windows.
import { parseFrontmatter } from '../tests/lib/frontmatter.mjs';
import { unifiedDiff } from './lib/diff.mjs';

// `--root <dir>` points every read at a fixture tree; without it, the repository this script
// lives in. The tests drive the CLI rather than the functions, because the exit code and the
// diff text are the product here — a test that called `render()` would not see either.
const argv = process.argv.slice(2);
const rootArg = argv.indexOf('--root');
const ROOT = resolve(rootArg === -1 ? resolve(dirname(fileURLToPath(import.meta.url)), '..') : argv[rootArg + 1]);
const TARGET = join(ROOT, 'docs', 'ARCHITECTURE.md');
const BEGIN = '<!-- ROSTER:BEGIN (generated by scripts/gen-roster.mjs — do not edit) -->';
const END = '<!-- ROSTER:END -->';

/**
 * Skills that are reference knowledge rather than a roster persona.
 *
 * Declared here AND derivable from the skill's `**Fires:**` line, and the generator fails if the
 * two disagree. One declaration would be enough to print the summary line; two that must agree is
 * what stops a reworded Fires line from silently turning the companion into an ordinary on-demand
 * skill and moving the persona count. Same idiom as the server key's four declarations (L07).
 */
const REFERENCE_SKILLS = new Set(['now-assist-genai']);

/**
 * How a skill's `**Fires:**` prose maps to the roster's six classifications.
 *
 * Ordered: the first match wins, because several lines say two true things. `atf-author` fires
 * post-build "and on demand" — post-build is the one that puts it in the protocol, so it is
 * checked first. A line that matches nothing is a hard failure (below), never `unknown`: an
 * unclassifiable skill is a skill whose triggers nobody can look up, and printing a placeholder
 * would put that in a published table.
 */
const FIRES_RULES = [
  ['gateway', /Phase 1 Step 5/i],
  ['reference', /to ground the/i],
  ['post-build consult', /post-build per taxonomy/i],
  ['routing-time consult', /routing-time consult|§3\.1/i],
  ['builder', /On dispatch from the Chief Architect/i],
  ['on demand', /on demand|upstream of the whole routing protocol/i],
];

const fail = (message) => { process.stderr.write(`gen-roster: ${message}\n`); process.exit(2); };
const posix = (p) => p.split('\\').join('/');
const lf = (s) => s.replace(/\r\n/g, '\n');

function read(rel) {
  const p = join(ROOT, rel);
  if (!existsSync(p)) fail(`${posix(rel)} is missing`);
  return readFileSync(p, 'utf8');
}

function classify(firesLine, rel) {
  for (const [label, re] of FIRES_RULES) if (re.test(firesLine)) return label;
  fail(`${posix(rel)}: the **Fires:** line matches no classification — ${JSON.stringify(firesLine)}.\n`
    + '  Add a rule to FIRES_RULES, or word the line like the others. It is never guessed.');
  return null;
}

function collectSkills() {
  const dir = join(ROOT, '.claude', 'skills');
  const names = readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory()).map((e) => e.name).sort();
  return names.map((name) => {
    const rel = `.claude/skills/${name}/SKILL.md`;
    const text = lf(read(rel));
    const { data } = parseFrontmatter(text, rel);
    const fires = text.split('\n').find((l) => l.startsWith('**Fires:**'));
    // S03 made `## Triggers` the first H2 with all three fields; a missing line is that
    // contract broken, and the generator says so rather than papering over it.
    if (!fires) fail(`${posix(rel)}: no "**Fires:**" line — S03 requires one in ## Triggers`);
    const firesAs = classify(fires.replace('**Fires:**', '').trim(), rel);
    const declaredReference = REFERENCE_SKILLS.has(name);
    if (declaredReference !== (firesAs === 'reference')) {
      fail(`${posix(rel)}: classified "${firesAs}" from its **Fires:** line, but REFERENCE_SKILLS `
        + `${declaredReference ? 'lists' : 'does not list'} it. The two declarations must agree — `
        + 'reword the line or change the set, deliberately.');
    }
    return {
      name: data.name ?? name,
      dir: name,
      description: data.description ?? '',
      version: data.metadata?.version ?? '',
      firesAs,
      isReference: declaredReference,
    };
  });
}

function collectAgents() {
  const dir = join(ROOT, '.claude', 'agents');
  const files = readdirSync(dir).filter((f) => f.endsWith('.md')).sort();
  return files.map((file) => {
    const rel = `.claude/agents/${file}`;
    const { data } = parseFrontmatter(lf(read(rel)), rel);
    const skills = Array.isArray(data.skills) ? data.skills : [data.skills].filter(Boolean);
    return { name: data.name ?? file.replace(/\.md$/, ''), description: data.description ?? '', skills };
  });
}

const cell = (s) => String(s).replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();

function render({ skills, agents, utility }, firstSentence) {
  const roster = skills.filter((s) => !utility.has(s.dir));
  const personas = roster.filter((s) => !s.isReference);
  // An agent's PERSONA, not everything it preloads. `now-assist-specialist` also preloads
  // `now-assist-genai`, and the companion having a sub-agent is precisely what it does not have —
  // it is reference knowledge loaded alongside a builder. The preload is still visible in the
  // sub-agent table's own column, where it says what it is.
  const withAgent = new Set(agents.map((a) => a.name));
  const companions = roster.filter((s) => s.isReference).map((s) => s.name).join(', ');

  const out = [BEGIN, ''];
  // Every number here is counted, never typed. The parenthetical names the companion so a reader
  // can see why the two totals differ by one.
  out.push(`**${personas.length} specialist personas · ${roster.length} skills`
    + `${companions ? ` (incl. ${companions} reference companion)` : ''}`
    + ` · ${agents.length} sub-agents**`, '');

  out.push('### Skills', '', '| Skill | Fires as | Sub-agent | Version |', '|---|---|---|---|');
  for (const s of roster) {
    out.push(`| \`${cell(s.name)}\` | ${cell(s.firesAs)} | ${withAgent.has(s.name) ? 'yes' : '—'} `
      + `| ${cell(s.version)} |`);
  }

  out.push('', '### Sub-agents', '', '| Agent | Preloads | What it does |', '|---|---|---|');
  for (const a of agents) {
    const preloads = a.skills.map((s) => `\`${cell(s)}\``).join(', ') || '—';
    out.push(`| \`${cell(a.name)}\` | ${preloads} | ${cell(firstSentence(a.description))} |`);
  }

  out.push('', '### Utility skills', '', '| Skill | Version |', '|---|---|');
  const utilityRows = skills.filter((s) => utility.has(s.dir));
  for (const s of utilityRows) out.push(`| \`${cell(s.name)}\` | ${cell(s.version)} |`);
  if (utilityRows.length === 0) {
    // The heading and the empty table are generated while `roster.utility` is empty, so
    // ARC-02-S11 adds `snowarch` to the config and changes no generator code (ruling 2).
    out.push('', '*None yet — ARC-02-S11 adds `snowarch`.*');
  }

  out.push('', END);
  return out.join('\n');
}


async function main() {
  const { firstSentence } = await import('./lib/text.mjs');

  const config = JSON.parse(read('engine.config.json'));
  const roster = config.roster ?? {};
  // `roster.utility` does not exist yet; ARC-02-S11 adds it. Absent means empty, not an error.
  const utility = new Set(roster.utility ?? []);

  const skills = collectSkills();
  const agents = collectAgents();
  const model = { skills, agents, utility };

  const problems = [];
  const rosterSkills = skills.filter((s) => !utility.has(s.dir));
  if (roster.skills !== undefined && roster.skills !== rosterSkills.length) {
    problems.push(`roster.skills ${roster.skills} ≠ ${rosterSkills.length} found`);
  }
  if (roster.agents !== undefined && roster.agents !== agents.length) {
    problems.push(`roster.agents ${roster.agents} ≠ ${agents.length} found`);
  }
  const known = new Set(skills.map((s) => s.name));
  for (const a of agents) {
    for (const s of a.skills) {
      if (!known.has(s)) problems.push(`.claude/agents/${a.name}.md preloads "${s}", which is not a skill`);
    }
    // AG-05: the persona arrives through frontmatter. An agent that does not preload the skill of
    // its own name has no persona, and the "Sub-agent" column above would then be claiming one.
    if (!a.skills.includes(a.name)) {
      problems.push(`.claude/agents/${a.name}.md does not preload its own persona skill "${a.name}"`);
    }
  }

  if (argv.includes('--json')) {
    process.stdout.write(`${JSON.stringify({ ...model, utility: [...utility], problems }, null, 2)}\n`);
    process.exit(problems.length > 0 ? 1 : 0);
  }

  const block = render(model, firstSentence);
  const doc = read('docs/ARCHITECTURE.md');
  const start = doc.indexOf(BEGIN);
  const stop = doc.indexOf(END);
  if (start === -1 || stop === -1 || stop < start) {
    fail('docs/ARCHITECTURE.md has no ROSTER:BEGIN / ROSTER:END block — add the two markers first');
  }
  const current = doc.slice(start, stop + END.length);
  const next = doc.slice(0, start) + block + doc.slice(stop + END.length);

  if (argv.includes('--check')) {
    // LF-normalised on both sides: the Windows cell checks out with CRLF and the file is
    // otherwise identical, which is not a diff anybody can act on (criterion 5).
    const stale = lf(current) !== lf(block);
    if (stale) process.stdout.write(`${unifiedDiff(lf(current), lf(block), 'docs/ARCHITECTURE.md')}\n`);
    for (const p of problems) process.stdout.write(`gen-roster: ${p}\n`);
    if (stale || problems.length > 0) {
      process.stdout.write('gen-roster: run `node scripts/gen-roster.mjs` and commit the result\n');
      process.exit(1);
    }
    process.stdout.write(`gen-roster: docs/ARCHITECTURE.md roster block is current `
      + `(${rosterSkills.length} skills, ${agents.length} agents, ${utility.size} utility)\n`);
    process.exit(0);
  }

  for (const p of problems) process.stdout.write(`gen-roster: ${p}\n`);
  if (problems.length > 0) process.exit(1);
  writeFileSync(TARGET, next);
  process.stdout.write(`gen-roster: wrote docs/ARCHITECTURE.md `
    + `(${rosterSkills.length} skills, ${agents.length} agents, ${utility.size} utility)\n`);
}

main();
