// ARC-11-C1 — the licence core: canonical JSON, the detached Ed25519 signature, the states.
//
// Every key here is generated by the test that uses it and injected as the product's key list. No
// key is ever committed for a test: the shipped list is the owner's two public keys and nothing else,
// and `licence-keys-guard.test.mjs` holds that. A test that signed with a committed development key
// would pass against a product that trusted that key, which is the one product this must never be.
import { test } from 'node:test';
import assert from 'node:assert/strict';

import {
  canonicalJson, checkLicence, EXPIRING_DAYS, fingerprint, LICENCE_FORMAT, LIST_FORMAT, newerList,
  readList, signLicence,
} from '../lib/licence/core.mjs';
import { keyPair, licence, licenceText, listDoc as signedList, productKeys } from './helpers/licence.mjs';

const primary = keyPair();
const recovery = keyPair();
const stranger = keyPair();
const KEYS = productKeys(primary, recovery);

const NOW = new Date('2026-10-10T12:00:00Z');

const fileText = (payload, key = primary) => licenceText(payload, key);

const check = (text, opts = {}) => checkLicence(text, { keys: KEYS, now: NOW, list: null, ...opts });

test('ARC-11-C1 — canonical JSON sorts keys at every depth and writes no whitespace', () => {
  assert.equal(canonicalJson({ b: 1, a: { d: [3, { f: 1, e: 2 }], c: 'x' } }),
    '{"a":{"c":"x","d":[3,{"e":2,"f":1}]},"b":1}');
  assert.equal(canonicalJson({ z: 1, a: 2 }), canonicalJson({ a: 2, z: 1 }));
  assert.equal(canonicalJson({ a: undefined, b: null }), '{"b":null}');
  assert.equal(canonicalJson({ org: 'Тест ООД — Ünïcödé' }), '{"org":"Тест ООД — Ünïcödé"}');
  assert.throws(() => canonicalJson({ n: Number.NaN }), /finite/);
});

test('ARC-11-C1 — a licence signed by the primary key is ok, and says which key signed it', () => {
  const doc = signLicence(licence(), primary.privateKey);
  assert.equal(doc.format, LICENCE_FORMAT);
  assert.equal(doc.signature.alg, 'Ed25519');
  assert.equal(doc.signature.key, fingerprint(primary.publicKey));
  const s = check(fileText(licence()));
  assert.equal(s.state, 'ok');
  assert.equal(s.id, 'LIC-2026-0002');
  assert.equal(s.scope, 'live');
  assert.equal(s.key, 'primary');
  assert.equal(s.signatureValid, true);
  assert.equal(s.validUntil, '2027-10-10');
  assert.equal(s.perpetual, false);
});

test('ARC-11-C1 — forgery: an edited date, an edited name or an edited signature is invalid', () => {
  const doc = JSON.parse(fileText(licence()));
  const later = structuredClone(doc);
  later.licence.valid_until = '2099-12-31';
  const renamed = structuredClone(doc);
  renamed.licence.licensee = 'Somebody Else';
  const scribbled = structuredClone(doc);
  scribbled.signature.value = Buffer.alloc(64, 7).toString('base64');
  for (const forged of [later, renamed, scribbled]) {
    const s = check(JSON.stringify(forged));
    assert.equal(s.state, 'invalid');
    assert.match(s.reason, /signature/);
    assert.equal(s.signatureValid, false);
    assert.equal(s.id, null, 'an id is reported only from a licence whose signature holds');
  }
});

test('ARC-11-C1 — a key the product does not ship signs nothing, whatever fingerprint it claims', () => {
  assert.equal(check(fileText(licence(), stranger)).state, 'invalid');
  assert.match(check(fileText(licence(), stranger)).reason, /not signed by a key this product ships/);
  // The stranger signs, and the file CLAIMS the primary key: the claim is checked, not believed.
  const claimed = signLicence(licence(), stranger.privateKey);
  claimed.signature.key = fingerprint(primary.publicKey);
  assert.equal(check(JSON.stringify(claimed)).state, 'invalid');
});

test('ARC-11-C1 — a licence signed by the recovery key verifies (R3: the creator always has access)', () => {
  const s = check(fileText(licence(), recovery));
  assert.equal(s.state, 'ok');
  assert.equal(s.key, 'recovery');
});

test('ARC-11-C1 — a licence with no valid_until is perpetual, and only a product key can sign one', () => {
  const { valid_until: _, ...forever } = licence({ id: 'LIC-2026-0001', notes: 'creator' });
  const s = check(fileText(forever));
  assert.equal(s.state, 'ok');
  assert.equal(s.perpetual, true);
  assert.equal(s.validUntil, null);
  assert.equal(s.daysLeft, null);
  assert.equal(check(fileText(forever, recovery)).state, 'ok');
  assert.equal(check(fileText(forever, stranger)).state, 'invalid');
});

test('ARC-11-C1 — expiry: the valid_until day is inclusive, in UTC, and the last 30 days are expiring', () => {
  const at = (date, now) => check(fileText(licence({ valid_until: date })), { now: new Date(now) });
  assert.equal(EXPIRING_DAYS, 30);
  const lastSecond = '2026-10-10T23:59:59Z';
  assert.deepEqual([at('2026-10-10', lastSecond).state, at('2026-10-10', lastSecond).daysLeft], ['expiring', 0]);
  assert.equal(at('2026-10-09', lastSecond).state, 'expired');
  assert.equal(at('2026-10-10', '2026-10-11T00:00:00Z').state, 'expired');
  assert.deepEqual([at('2026-11-09', lastSecond).state, at('2026-11-09', lastSecond).daysLeft], ['expiring', 30]);
  assert.equal(at('2026-11-10', lastSecond).state, 'ok');
  assert.equal(at('2026-10-09', lastSecond).signatureValid, true, 'an expired licence is still authentic');
});

test('ARC-11-C1 — no file is missing; a file that is not a licence is invalid', () => {
  const missing = check(null);
  assert.equal(missing.state, 'missing');
  assert.equal(missing.signatureValid, false);
  assert.equal(missing.id, null);
  for (const text of ['not json', '{}', JSON.stringify({ format: 'something/1', licence: licence(), signature: {} })]) {
    assert.equal(check(text).state, 'invalid', text);
  }
  // Shape is checked even under a good signature: a product key that signed a malformed licence
  // has still not issued a licence.
  for (const bad of [licence({ id: 'LIC-26-1' }), licence({ scope: 'enterprise' }),
    licence({ issued: '2026-10-10', valid_until: '2026-10-09' }), licence({ issued: '10/10/2026' }),
    licence({ licensee: '' })]) {
    assert.equal(check(fileText(bad)).state, 'invalid', JSON.stringify(bad));
  }
});

test('ARC-11-C1 — an empty key list verifies nothing, so every licence is invalid until the keys ship', () => {
  assert.equal(check(fileText(licence()), { keys: [] }).state, 'invalid');
  assert.equal(check(null, { keys: [] }).state, 'missing');
});

const listDoc = (list, key = primary) => signedList(list, key);

test('ARC-11-C1 — revocation: a hit is revoked with its reason; a miss changes nothing', () => {
  const doc = listDoc({ version: 2, revoked: [{ id: 'LIC-2026-0002', revokedAt: '2026-10-11', reason: 'ended' }] });
  assert.equal(doc.format, LIST_FORMAT);
  const list = readList(doc, { keys: KEYS });
  assert.equal(list.ok, true);
  assert.equal(list.version, 2);
  const hit = check(fileText(licence()), { list });
  assert.equal(hit.state, 'revoked');
  assert.deepEqual(hit.revocation, { revokedAt: '2026-10-11', reason: 'ended' });
  assert.equal(hit.signatureValid, true);
  assert.equal(hit.id, 'LIC-2026-0002');
  assert.equal(check(fileText(licence({ id: 'LIC-2026-0003' })), { list }).state, 'ok');
});

test('ARC-11-C1 — a list is read only when a product key signed it and it says nothing but id, date and reason', () => {
  const entry = { id: 'LIC-2026-0002', revokedAt: '2026-10-11', reason: 'lost' };
  assert.equal(readList(listDoc({ version: 1, revoked: [entry] }, recovery), { keys: KEYS }).ok, true);
  const refused = [
    listDoc({ version: 1, revoked: [entry] }, stranger),
    listDoc({ version: 1, revoked: [{ ...entry, licensee: 'Test Licensee' }] }),
    listDoc({ version: 1, revoked: [{ ...entry, reason: 'they asked nicely' }] }),
    listDoc({ version: 0, revoked: [] }),
    listDoc({ version: 1.5, revoked: [] }),
    listDoc({ version: 1, revoked: [entry, entry] }),
    { format: LIST_FORMAT, list: { version: 1, revoked: [] } },
  ];
  for (const doc of refused) assert.equal(readList(doc, { keys: KEYS }).ok, false, JSON.stringify(doc.list));
  const forged = listDoc({ version: 1, revoked: [entry] });
  forged.list.revoked = [];
  assert.equal(readList(forged, { keys: KEYS }).ok, false, 'an entry removed after signing');
  assert.equal(readList('not json', { keys: KEYS }).ok, false);
});

test('ARC-11-C1 — rollback: a list whose version is not higher than the one held is ignored', () => {
  const v = (n) => readList(listDoc({ version: n, revoked: [] }), { keys: KEYS });
  assert.equal(newerList(v(3), v(2)).version, 3);
  assert.equal(newerList(v(2), v(3)).version, 3);
  assert.equal(newerList(null, v(1)).version, 1);
  assert.equal(newerList(v(2), null).version, 2);
  assert.equal(newerList(null, null), null);
  const held = v(2);
  assert.equal(newerList(held, v(2)), held, 'an equal version keeps the list already held');
});
