// ARC-09-S06 — the ROOT ENTRY for `store`, run as a process, with real options.
//
// The unit tests next door prove the argv the forwarder composes. This one types the arguments,
// through the launcher a user actually runs, because the failure they cannot catch is the frame
// eating a flag on the way: `./snowarch instance add … --yes` once answered "--yes needs a value"
// from the ENGINE's parser with every unit test green, and `store restore <file> --yes` is the
// same shape.
//
// Every assertion is about WHOSE answer arrived. The exit table and the backup sentence exist
// only in the server CLI; the one-line usage exists only in the engine.
import assert from 'node:assert/strict';
import { spellings } from '../lib/text.mjs';
import { cliSpelling } from '../../../packages/snowarch/dist/cli/tty.js';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

import { preconditions } from '../lib/instance.mjs';
import { useStateRoot } from './helpers/state-root.mjs';
/*
 * ARC-07-C43 head 2 — THIS SUITE RUNS THE REAL CLI, so its `.local/` goes somewhere else.
 *
 * Measured: with this line absent, a full `npm test` leaves logs and the doctor/upgrade caches in the
 * repository's own `.local/`, which is gitignored and therefore invisible to `assert-clean`. A `cwd`
 * cannot fix it — `root` comes from `config.mjs`'s own location — so the state root is what moves.
 */
useStateRoot();


const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');

const ENTRIES = [
  { name: 'the engine entry', argv0: process.execPath, lead: [join(root, 'tools/snowarch/bin/snowarch.mjs')] },
  ...(process.platform === 'win32'
    // `call`, because a `.cmd` invoked without it transfers control and never comes back — the
    // lesson S04's CI cell learned the hard way.
    ? [{ name: 'snowarch.cmd', argv0: process.env.COMSPEC || 'cmd.exe', lead: ['/c', 'call', join(root, 'snowarch.cmd')] }]
    : [{ name: './snowarch', argv0: join(root, 'snowarch'), lead: [] }]),
];

const run = (entry, args, env = {}) => {
  const r = spawnSync(entry.argv0, [...entry.lead, ...args],
    { encoding: 'utf8', cwd: root, env: { ...process.env, ...env } });
  return { status: r.status, text: `${r.stdout ?? ''}${r.stderr ?? ''}` };
};

test('the server CLI can run from this checkout — the precondition for every row below', () => {
  const check = preconditions({ root });
  assert.equal(check.ok, true, check.problems.join(' · '));
});

/**
 * The launcher, escaped for a RegExp — ARC-07-W17. `RegExp.escape` is not on Node 20.
 *
 * Both helps name it through the definitions now, so a POSIX literal in either assertion would fail
 * the four Windows cells while every mac and Linux cell passed: the shape that took #308 red.
 */
/**
 * PINNED POSIX, AND CITING ARC-07-C31 — corrected after the Windows cells.
 *
 * Both usage lines here come from the ENGINE's frame, `tools/snowarch/lib/store.mjs`, which is
 * GENERATED by `gen-cli-help` and is still on ARC-07-C31's exemption list — so the product prints
 * `usage: ./snowarch store <command>` on every platform, including Windows. Deriving from the process
 * made this case expect `.\snowarch.cmd` under pwsh while the product correctly printed POSIX: the
 * test was wrong and the product was right, which is the shape rule 1 names.
 *
 * When C31 sweeps that generator, this pin flips with it — one line, in the same commit.
 */
const esc = (cli) => cli.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/**
 * TWO SPELLINGS, BECAUSE TWO PACKAGES PRINT HERE — ARC-07-W17, rule 6.
 *
 * My first version used one, pinned POSIX, with a comment claiming "both usage lines come from the
 * ENGINE's frame". Only the first does. `store --help` is answered by the frame,
 * `tools/snowarch/lib/store.mjs:16`, a POSIX literal still on ARC-07-C31's list — so it prints POSIX on
 * every platform and its expectation is pinned. `store migrate --help` is answered by the SERVER,
 * `packages/snowarch/src/cli/store-command.ts:48`, which reads `cliSpelling()` — so under pwsh it prints
 * `.\snowarch.cmd store <command>` and a pinned expectation fails there.
 *
 * THE RULE THIS COST: classify per ASSERTED LINE, by the product line that prints it — not per file, and
 * not per test. One test can print from both packages in two commands, and this one does.
 */
const FRAME_CLI = esc(spellings({ platform: 'linux', env: {} }).cli);
/**
 * ARC-07-C31 slice 3 — REPOINTED AT THE SERVER'S OWN DEFINITION, because that is what prints these
 * lines.
 *
 * It derived from the engine's `spellings()`, which computes the same answer from the same process, so
 * it agreed and nothing failed. Agreement is not the property: rule 1 is that a test derives from the
 * SAME SOURCE the product line used, and a server line is spelled by `cliSpelling()` in
 * `packages/snowarch/src/cli/tty.ts`. Reading it from the server's `dist/` is the one direction the
 * package boundary allows, and it means the day the two definitions disagree this file follows the
 * one that is actually printing.
 */
const SERVER_CLI = esc(cliSpelling());

for (const entry of ENTRIES) {

  test(`${entry.name}: a bare --help is the ENGINE's one-liner`, () => {
    const r = run(entry, ['store', '--help']);
    assert.equal(r.status, 0);
    assert.match(r.text, new RegExp(`usage: ${FRAME_CLI} store <command>`));
  });

  test(`${entry.name}: \`migrate --help\` is the SERVER's help, with the exit table`, () => {
    const r = run(entry, ['store', 'migrate', '--help']);
    assert.equal(r.status, 0, r.text);
    // ARC-07-W17 — THE USAGE LINE IS NO LONGER THE DISCRIMINATOR, AND IT SHOULD NEVER HAVE BEEN.
    //
    // This test told the two helps apart by the ENGINE printing `usage: ./snowarch store <command>`
    // and the SERVER printing `usage: snowarch store <command>` — so what distinguished whose answer
    // arrived was the server's bare name, which is the defect W17 closes. A test resting on a defect
    // goes green when the defect is fixed only if its discriminator moves, and this one had two
    // better ones already: `exit codes:` and the backup sentence exist ONLY in the server CLI, and
    // the header comment at the top of this file says exactly that.
    assert.match(r.text, new RegExp(`usage: ${SERVER_CLI} store <command>`));
    assert.match(r.text, /exit codes:/);
    assert.match(r.text, /never pruned automatically/);
  });

  test(`${entry.name}: \`migrate --yes\` reaches the server as a FLAG, not a value`, () => {
    const dir = mkdtempSync(join(tmpdir(), 'store-root-entry-'));
    try {
      const store = join(dir, 'instances.json');
      writeFileSync(store, `${JSON.stringify({ version: 1, instances: {} }, null, 2)}\n`);
      const r = run(entry, ['store', 'migrate', '--yes'], { SNOW_STORE: store });
      assert.equal(r.status, 0, r.text);
      assert.match(r.text, /schema v1 is current — nothing to do/);
      // The two wrong answers this test exists to keep out.
      assert.doesNotMatch(r.text, /needs a value/);
      assert.doesNotMatch(r.text, /not installed yet/);
    } finally { rmSync(dir, { recursive: true, force: true }); }
  });

  test(`${entry.name}: an unreadable store exits 1 through the launcher, and writes nothing`, () => {
    const dir = mkdtempSync(join(tmpdir(), 'store-root-entry-bad-'));
    try {
      const store = join(dir, 'instances.json');
      writeFileSync(store, '{ hand-edited\n');
      const r = run(entry, ['store', 'migrate', '--yes'], { SNOW_STORE: store });
      assert.equal(r.status, 1, r.text);
      assert.match(r.text, /STORE_UNREADABLE/);
      // ARC-07-C31 slice 3 — the SERVER's `parseStore` sentence, which derives now. A POSIX literal
      // here was green on a mac and red on two Windows cells: `…restore a backup
      // (.\snowarch.cmd store backups)`. Escaped, because the spelling contains `.` and `\`.
      assert.match(r.text, new RegExp(`${SERVER_CLI} store backups`));
    } finally { rmSync(dir, { recursive: true, force: true }); }
  });

  test(`${entry.name}: an unknown sub-command is the SERVER's refusal`, () => {
    const r = run(entry, ['store', 'frobnicate']);
    assert.equal(r.status, 2);
    assert.match(r.text, /migrate, backups or restore/);
  });
}
