/**
 * L03 — no engine text uses a name the server rejects.
 *
 * The list is `retired-names.json`, generated by ARC-05-S02 from three sources. Two rules make
 * this usable rather than merely strict:
 *
 *  - A **tool name** is never exempt. A historical marker cannot make `snow_rpt_report_generate`
 *    safe to cite: the server answers it with `UNKNOWN_TOOL` whatever the sentence around it
 *    says.
 *  - An **identifier** may be named on a marked line, and only in the three files where naming
 *    the past is the job: `docs/ARCHITECTURE.md`, `docs/decisions/**`, `docs/CHANGELOG.md`.
 */
import { HISTORICAL_MARKER, honoursMarker, isHistory, readLines } from '../lib/scan.mjs';

export const id = 'L03';
export const title = 'no retired name outside the files whose subject is the past';

const escape = (key) => key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** Word-boundary for identifier-shaped keys; literal for keys with `/` or `-`. */
const pattern = (key) => (/^[A-Za-z0-9_]+$/.test(key)
  ? `\\b${escape(key)}\\b`
  : escape(key));

function makeMatcher(key) {
  return new RegExp(pattern(key));
}

export function run(ctx) {
  const entries = Object.entries(ctx.retiredNames).map(([key, replacement]) => ({
    key,
    replacement,
    isTool: key.startsWith('snow_'),
    re: makeMatcher(key),
  }));

  // One alternation over every key, used only to decide whether a line is worth looking at.
  // Without it this check is 400-odd regex passes over every line of every scanned file and
  // costs ~2 s of the lint's ~3 s; with it, the ~99% of lines that mention nothing retired cost
  // a single pass. The per-entry loop below still produces the findings, so the output — and
  // its order — is unchanged; this only decides which lines reach it.
  const any = new RegExp(entries.map((e) => pattern(e.key)).join('|'));

  const findings = [];
  for (const file of ctx.files) {
    if (isHistory(file)) continue;
    const marked = honoursMarker(file);
    const lines = readLines(ctx.root, file);

    lines.forEach((line, i) => {
      if (!any.test(line)) return;
      const isMarkedLine = marked && line.trimEnd().endsWith(HISTORICAL_MARKER);
      for (const e of entries) {
        if (!e.re.test(line)) continue;
        // The marker excuses an identifier, never a tool name.
        if (isMarkedLine && !e.isTool) continue;
        findings.push({
          file,
          line: i + 1,
          message: `retired name "${e.key}" → use ${e.replacement}`,
        });
      }
    });
  }
  return findings;
}
